### ISSUE TITLE
IncludeOptional for conf.d ... is there a reason why this is not there?

### ISSUE THREAD

**Issue by rmalchow** [docker-library/httpd#143] opened 2019-08-12 11:49 UTC
hi,

we use the base httpd image sometimes to have a quick webserver. one thing that would really, really help (and make the base image much more flexible) would be something like 

`IncludeOptional` /usr/local/apache2/conf/conf.d/*.conf

which, by default, would be empty of course. however, it would provide and easy hook for adding some custom configuration options. this would be much appreciated.

seeing that it is not there, i was wondering if this is by design? or just a plain oversight? 

thanks

.rm

**Comment by tianon** [comment] 2019-08-12 22:44
It's by design that *we* don't include this, but I can't speak for upstream:

https://github.com/docker-library/httpd/blob/385f0d1d8e09fd44c9b083fa390a8b1f09e1a33a/2.4/Dockerfile#L126-L132

This is the only modification we make to the default configuration supplied by `httpd` upstream -- namely, switching the default logging to use stdout/stderr (as is normal for container images) instead of files.

**Comment by rmalchow** [comment] 2019-08-13 09:37
hi, 

thank you for your answer. doing this include would be a nice addition though, which makes much more sense in a docker image than in a standalone binary - somewhat comparable to the change in logging. i just created a PR. 

https://github.com/docker-library/httpd/pull/144

maybe this does make sense? if not, feel free to ignore :)

thanks

.rm

**Comment by gregsidelinger** [comment] 2019-08-26 02:15
I would love to see this included by default.  With kubernetes I use configmaps to store my specific configurations and use volumes to mount them at run time. I do not always need to build an image however you are forcing me to aways extend your image just to add a few config files.

**Comment by rmalchow** [comment] 2019-08-26 08:06
@tianon any opinion on this?

**Comment by rmalchow** [comment] 2019-08-26 20:29
hi tianon - well ... upstream (i.e. vanilla install from tgz) it is super easy to add it manually. with a docker image, it's nice to have an optional hook (as greg said, and i would appreciate it for the same reason).

**Comment by tianon** [comment] 2020-06-24 18:48
Closing as a duplicate of #105; see especially https://github.com/docker-library/httpd/pull/105#issuecomment-408918821 and https://github.com/docker-library/httpd/pull/105#issuecomment-434514664 for trivial ways to accomplish this both with a simple `Dockerfile` and without a `Dockerfile` (using the vanilla published image as-is).

**Closed by tianon** 2020-06-24 18:48 UTC
Labels: Request
