### ISSUE TITLE
Serving large files causes dropped content

### ISSUE THREAD

**Issue by Sub-Xaero** [docker-library/httpd#60] opened 2017-06-23 22:13 UTC
I have a web project that I am currently serving through Docker httpd:latest. 
Said web project has a gulp build that concatenates all third party libraries into a single monolithic lib.js file of 3.21MB. 

I have a "very" consistent issue with httpd, where simply loading a page with not much content other than the library file presents a host of seemingly random JavaScript errors that change every time you reload the page. Upon further investigation, the issue is that snippets of the file just go missing in transfer, and lines of code just disappear from the file. 

By sheer dumb luck, and force reloading the page again and again, I have tested the consistency of this, by running HTTPD outside of Docker, and the page loads fine, and tested in NGINX, inside and outside of Docker, and the page loads fine. It is only in the docker version of the server that this issue occurs. 

I would suggest that it is something to do with the content stream timing out, or packets getting lost. But I can only vouch for the symptoms.

**Comment by tianon** [comment] 2018-05-07 22:53
Sorry for the delay.  Do you think this is an issue in the way we've compiled httpd (or the default configuration supplied by the project), or an issue in Docker and/or Linux itself (and thus outside the control of this image)?

**Comment by Sub-Xaero** [comment] 2018-05-08 07:27
Well, running Apache outside of Docker with the default config and the same files, does not have the same problem. And switching over to an NGINX image within Docker eliminates the problem too.


Whereas Docker httpd with a default config, times out sporadically when serving large files, i.e. several MB js asset bundles.




So its definitely something about running Apache httpd inside Docker, whether that's the Apache config, or something about the executable that has been compiled differently to the main (uncontainerised) server, that is causing the problem.






From: Tianon Gravi


Sent: Monday 7 May, 23:53


Subject: Re: [docker-library/httpd] Serving large files causes dropped content (#60)


To: docker-library/httpd


Cc: Dylan Clarke, Author






Sorry for the delay. Do you think this is an issue in the way we've compiled httpd (or the default configuration supplied by the project), or an issue in Docker and/or Linux itself (and thus outside the control of this image)?

**Comment by tianon** [comment] 2018-05-08 20:11
Can this be reproduced with a Docker image that installs Apache from Debian instead? (to isolate whether it's an issue with this image or rather a general issue with Docker)

**Comment by EkoMcCloud** [comment] 2018-07-12 11:50
Hi! I'm having a smilar issue with the latest version. One of my project development setup load an uncompiled version of angular.js for debug purpose. The file is pretty large (>35k lines). 
I'm getting random syntax errors (generally happening around the 21 000th line) on reload.
When I inspect the file from a browser inpector I can sometime see weird characters appearing :

```
function register(name, factory) {
    if (isObject(name)) {
      var filters = {};
      forEach(name, function(filter, key) {X�SMB@{��d@|�K���匐��
�%0%0
        filters[key] = register(key, filter);
      });
      return filters;
    } else {
      return $provide.factory(name + suffix, factory);
    }
  }
```

There is absolutely no consistance in the bug, sometime I'll reload ten time in a row without any kind of trouble, sometime I'll get the error several times, the buggy characters are not always the same and does not appear every time at the same spot.

**Comment by Sub-Xaero** [comment] 2018-07-12 12:17
@tianon So a Dockerfile that simply runs `apt-get install apache2`? As opposed to building it from scratch?
I can try it, but I'm not sure I have the original source files, that were causing this to crash, in order to test it. Will report back if I find anything, seeing as other people are starting to have the same issue.

**Comment by jnugh** [comment] 2018-09-13 23:31
I noticed the same issue on some of our systems.
This happened for us on windows (docker for windows) systems with files served from a volume mounted to the host system.

Docker for windows mounts the volumes as CIFS which for some reason does not work correctly with `EnableMMAP`.

The Problem disappears on my test system with the directives:
```
EnableMMAP Off
EnableSendfile Off
```

**Comment by tianon** [comment] 2018-09-20 22:20
@jnugh good catch!  I think "Docker for Windows" uses its own file sharing solution, but I think it's got similar caveats to CIFS, so your solution is probably spot on. :+1:

Closing since it doesn't appear there's anything more we can do here (if you run into this issue, try the workaround noted above of disabling `MMAP` and `Sendfile` in your configuration).

**Closed by tianon** 2018-09-20 22:20 UTC
Labels: Issue

**Comment by EkoMcCloud** [comment] 2018-09-26 15:35
I've been working all day with `EnableMMAP Off` on my httpd configuration, it worked great, thanks for the workaround!

`EnableSendfile` seems to be off by default so it wasn't necessary on my configuration.
