### ISSUE TITLE
upgrade to openssl 1.1.0+

### ISSUE THREAD

**Issue by shreddd** [docker-library/httpd#98] opened 2018-04-06 21:45 UTC
There are a number of fixes in OpenSSL 1.1.0 but the httpd Dockerfile still uses 1.0.2. 

The issue we are seeing in our nessus scans: https://www.openssl.org/blog/blog/2016/08/24/sweet32/

Requesting an upgrade to a more current version of OpenSSL.

**Comment by J0WI** [comment] 2018-06-10 19:12
Duplicate of #85

**Comment by wglambert** [comment] 2018-08-30 20:06
Closing as duplicate

**Closed by wglambert** 2018-08-30 20:06 UTC
Labels: Request
