### ISSUE TITLE
Unable to pull httpd docker images

### ISSUE THREAD

**Issue by ryanschuhler** [docker-library/httpd#93] opened 2018-03-19 22:37 UTC
Right now when I run `docker pull httpd` I get the following error 

> Using default tag: latest
> latest: Pulling from library/httpd
> no matching manifest for linux/amd64 in the manifest list entries

Has something changed or broken in the library?

**Comment by Mikeks81** [comment] 2018-03-19 22:53
same here for httpd:2.4-alpine

**Comment by yosifkit** [comment] 2018-03-19 22:58
Duplicate of: https://github.com/docker-library/official-images/issues/3835

**Closed by yosifkit** 2018-03-19 22:58 UTC
